<span data-font_class="td-icon-logout"><i class="td-icon-logout"></i></span>
<span data-font_class="td-icon-down"><i class="td-icon-down"></i></span>
<span data-font_class="td-icon-left"><i class="td-icon-left"></i></span>
<span data-font_class="td-icon-right"><i class="td-icon-right"></i></span>
<span data-font_class="td-icon-up"><i class="td-icon-up"></i></span>
<span data-font_class="td-icon-views"><i class="td-icon-views"></i></span>
<span data-font_class="td-icon-menu-down"><i class="td-icon-menu-down"></i></span>
<span data-font_class="td-icon-left-arrow"><i class="td-icon-left-arrow"></i></span>
<span data-font_class="td-icon-right-arrow"><i class="td-icon-right-arrow"></i></span>
<span data-font_class="td-icon-menu-up"><i class="td-icon-menu-up"></i></span>
<span data-font_class="td-icon-search"><i class="td-icon-search"></i></span>
<span data-font_class="td-icon-user"><i class="td-icon-user"></i></span>
<span data-font_class="td-icon-menu-left"><i class="td-icon-menu-left"></i></span>
<span data-font_class="td-icon-menu-right"><i class="td-icon-menu-right"></i></span>
<span data-font_class="td-icon-star"><i class="td-icon-star"></i></span>
<span data-font_class="td-icon-mail"><i class="td-icon-mail"></i></span>
<span data-font_class="td-icon-behance"><i class="td-icon-behance"></i></span>
<span data-font_class="td-icon-blogger"><i class="td-icon-blogger"></i></span>
<span data-font_class="td-icon-delicious"><i class="td-icon-delicious"></i></span>
<span data-font_class="td-icon-deviantart"><i class="td-icon-deviantart"></i></span>
<span data-font_class="td-icon-digg"><i class="td-icon-digg"></i></span>
<span data-font_class="td-icon-dribbble"><i class="td-icon-dribbble"></i></span>
<span data-font_class="td-icon-evernote"><i class="td-icon-evernote"></i></span>
<span data-font_class="td-icon-facebook"><i class="td-icon-facebook"></i></span>
<span data-font_class="td-icon-flickr"><i class="td-icon-flickr"></i></span>
<span data-font_class="td-icon-forrst"><i class="td-icon-forrst"></i></span>
<span data-font_class="td-icon-googleplus"><i class="td-icon-googleplus"></i></span>
<span data-font_class="td-icon-instagram"><i class="td-icon-instagram"></i></span>
<span data-font_class="td-icon-lastfm"><i class="td-icon-lastfm"></i></span>
<span data-font_class="td-icon-linkedin"><i class="td-icon-linkedin"></i></span>
<span data-font_class="td-icon-mail-1"><i class="td-icon-mail-1"></i></span>
<span data-font_class="td-icon-myspace"><i class="td-icon-myspace"></i></span>
<span data-font_class="td-icon-path"><i class="td-icon-path"></i></span>
<span data-font_class="td-icon-paypal"><i class="td-icon-paypal"></i></span>
<span data-font_class="td-icon-pinterest"><i class="td-icon-pinterest"></i></span>
<span data-font_class="td-icon-reddit"><i class="td-icon-reddit"></i></span>
<span data-font_class="td-icon-rss"><i class="td-icon-rss"></i></span>
<span data-font_class="td-icon-share"><i class="td-icon-share"></i></span>
<span data-font_class="td-icon-skype"><i class="td-icon-skype"></i></span>
<span data-font_class="td-icon-soundcloud"><i class="td-icon-soundcloud"></i></span>
<span data-font_class="td-icon-spotify"><i class="td-icon-spotify"></i></span>
<span data-font_class="td-icon-stackoverflow"><i class="td-icon-stackoverflow"></i></span>
<span data-font_class="td-icon-steam"><i class="td-icon-steam"></i></span>
<span data-font_class="td-icon-stumbleupon"><i class="td-icon-stumbleupon"></i></span>
<span data-font_class="td-icon-tumblr"><i class="td-icon-tumblr"></i></span>
<span data-font_class="td-icon-twitter"><i class="td-icon-twitter"></i></span>
<span data-font_class="td-icon-vimeo"><i class="td-icon-vimeo"></i></span>
<span data-font_class="td-icon-windows"><i class="td-icon-windows"></i></span>
<span data-font_class="td-icon-wordpress"><i class="td-icon-wordpress"></i></span>
<span data-font_class="td-icon-yahoo"><i class="td-icon-yahoo"></i></span>
<span data-font_class="td-icon-youtube"><i class="td-icon-youtube"></i></span>
<span data-font_class="td-icon-vk"><i class="td-icon-vk"></i></span>
<span data-font_class="td-icon-grooveshark"><i class="td-icon-grooveshark"></i></span>
<span data-font_class="td-icon-star-empty"><i class="td-icon-star-empty"></i></span>
<span data-font_class="td-icon-star-half"><i class="td-icon-star-half"></i></span>
<span data-font_class="td-icon-close"><i class="td-icon-close"></i></span>
<span data-font_class="td-icon-read-down"><i class="td-icon-read-down"></i></span>
<span data-font_class="td-icon-comments"><i class="td-icon-comments"></i></span>
<span data-font_class="td-icon-mobile"><i class="td-icon-mobile"></i></span>
<span data-font_class="td-icon-whatsapp"><i class="td-icon-whatsapp"></i></span>
<span data-font_class="td-icon-commenting"><i class="td-icon-commenting"></i></span>
<span data-font_class="td-icon-close-mobile"><i class="td-icon-close-mobile"></i></span>
<span data-font_class="td-icon-modal-back"><i class="td-icon-modal-back"></i></span>
<span data-font_class="td-icon-modal-close"><i class="td-icon-modal-close"></i></span>
<span data-font_class="td-icon-category"><i class="td-icon-category"></i></span>
<span data-font_class="td-icon-block-header"><i class="td-icon-block-header"></i></span>
<span data-font_class="td-icon-home"><i class="td-icon-home"></i></span>
<span data-font_class="td-icon-print"><i class="td-icon-print"></i></span>
<span data-font_class="td-icon-telegram"><i class="td-icon-telegram"></i></span>
<span data-font_class="td-icon-line"><i class="td-icon-line"></i></span>
<span data-font_class="td-icon-viber"><i class="td-icon-viber"></i></span>
<span data-font_class="td-icon-plus"><i class="td-icon-plus"></i></span>
<span data-font_class="td-icon-minus"><i class="td-icon-minus"></i></span>
<span data-font_class="td-icon-dailymotion"><i class="td-icon-dailymotion"></i></span>
<span data-font_class="td-icon-twitch"><i class="td-icon-twitch"></i></span>
<span data-font_class="td-icon-xing"><i class="td-icon-xing"></i></span>
<span data-font_class="td-icon-ebay"><i class="td-icon-ebay"></i></span>
<span data-font_class="td-icon-acolade"><i class="td-icon-acolade"></i></span>
<span data-font_class="td-icon-backslash"><i class="td-icon-backslash"></i></span>
<span data-font_class="td-icon-bracket-square"><i class="td-icon-bracket-square"></i></span>
<span data-font_class="td-icon-circle-full"><i class="td-icon-circle-full"></i></span>
<span data-font_class="td-icon-circle-line"><i class="td-icon-circle-line"></i></span>
<span data-font_class="td-icon-circless"><i class="td-icon-circless"></i></span>
<span data-font_class="td-icon-comma-round"><i class="td-icon-comma-round"></i></span>
<span data-font_class="td-icon-comma-square"><i class="td-icon-comma-square"></i></span>
<span data-font_class="td-icon-hash"><i class="td-icon-hash"></i></span>
<span data-font_class="td-icon-linee"><i class="td-icon-linee"></i></span>
<span data-font_class="td-icon-pluss"><i class="td-icon-pluss"></i></span>
<span data-font_class="td-icon-point-comma-round"><i class="td-icon-point-comma-round"></i></span>
<span data-font_class="td-icon-point-comma-square"><i class="td-icon-point-comma-square"></i></span>
<span data-font_class="td-icon-point-round"><i class="td-icon-point-round"></i></span>
<span data-font_class="td-icon-point-square"><i class="td-icon-point-square"></i></span>
<span data-font_class="td-icon-quote-round"><i class="td-icon-quote-round"></i></span>
<span data-font_class="td-icon-quote-square"><i class="td-icon-quote-square"></i></span>
<span data-font_class="td-icon-romb-full"><i class="td-icon-romb-full"></i></span>
<span data-font_class="td-icon-romb-line"><i class="td-icon-romb-line"></i></span>
<span data-font_class="td-icon-romb-round-full"><i class="td-icon-romb-round-full"></i></span>
<span data-font_class="td-icon-romb-round-line"><i class="td-icon-romb-round-line"></i></span>
<span data-font_class="td-icon-rombs"><i class="td-icon-rombs"></i></span>
<span data-font_class="td-icon-slashh"><i class="td-icon-slashh"></i></span>
<span data-font_class="td-icon-star-full"><i class="td-icon-star-full"></i></span>
<span data-font_class="td-icon-star-line"><i class="td-icon-star-line"></i></span>
<span data-font_class="td-icon-translingual"><i class="td-icon-translingual"></i></span>
<span data-font_class="td-icon-upp"><i class="td-icon-upp"></i></span>
<span data-font_class="td-icon-vertical-line"><i class="td-icon-vertical-line"></i></span>